---
deployment:
  tasks:
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan migrate --force
    - php artisan view:clear
    - php artisan optimize
